# Generated by Django 2.2.5 on 2019-10-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pizo.png', upload_to='profile_pictures'),
        ),
    ]
