# Generated by Django 2.2.5 on 2019-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191009_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='account_pic.png', upload_to='profile_pictures'),
        ),
    ]
