# Generated by Django 2.2.5 on 2019-10-09 06:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_billingaddress_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='biling_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
