# Generated by Django 2.2.5 on 2019-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20191019_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'shirt'), ('SW', 'sport wear'), ('OS', 'out wear'), ('LW', 'Ladies watches'), ('MW', 'Mens watch'), ('MS', 'Mens Shoes'), ('PH', 'Smart Phones'), ('LP', 'Laptop')], max_length=2),
        ),
    ]
